version: "3.9"
services:
    jl-quickstart-mysql:
        image: mysql:8.0
        container_name: jl-quickstart-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: localhost
            MYSQL_DATABASE: jl_quickstart
        command: --init-file /mysql/init.sql
        volumes:
            - ./.docker/setup.sql:/mysql/init.sql
        networks:
            - jl-quickstart-network
    jl-quickstart-redis:
        image: redis:6.2.5
        container_name: jl-quickstart-redis
        ports:
            - "6379:6379"
        networks:
            - jl-quickstart-network
    jl-quickstart-mongodb:
        image: mongo:latest
        container_name: jl-quickstart-mongodb
        ports:
            - "27017:27017"
        networks:
            - jl-quickstart-network
    jl-quickstart-rabbitmq:
        image: rabbitmq:3.8.9-management
        container_name: jl-quickstart-rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - jl-quickstart-network
networks:
    jl-quickstart-network:
        driver: bridge
        name: jl-quickstart-network